### DISCUSSION TITLE
NEAR Indexer Framework 0.9.2 release notes

### DISCUSSION THREAD

**Discussion by khorolets** [near/nearcore#4385] [Node Public Interfaces]
*edited 5 Jul, 2021*: updated commit hash and release dates along with breaking change notice.

*nearcore release **1.20.0** (going to be released Jul 5, 2021 testnet and Jul 12, 2021 mainnet)*

> Recommended commit
> **Commit hash: [9655ff694e8c38277b184ca42dc3478bbd4fd86a](https://github.com/near/nearcore/commit/9655ff694e8c38277b184ca42dc3478bbd4fd86a)**
> At the moment of writing this release notes there is no created release for nearcore 1.20.0 or RC
> You will be able to use the commit hash from release when it is created

## Release notes

* Delayed local receipts tracking system introduced in NEAR Indexer Framework 0.9.1 was optimized because previous was using recursion and could get into troubles

**Small breaking change** in this release, init_configs` function from nearcore has been extended with additional optional parameter `max_gas_burnt_view`. You'll need to provide a value to `near_indexer::init_configs()` call (the field is optional and you can pass `None`)
 Also we expect that some of the dependencies related to `actix` might ask to be upgraded.

```toml
actix = "=0.11.0-beta.2"
actix-web = "=4.0.0-beta.6"
actix-http = "=3.0.0-beta.6"
actix-tls = "=3.0.0-beta.5"
actix_derive = "=0.6.0-beta.1"
```

Feel free to leave questions in the comments below.
