### ISSUE TITLE
Fix `no_cache` feature and recompute fees

### ISSUE THREAD

**Issue by nearmax** [near/nearcore#2948]
According to https://github.com/nearprotocol/nearcore/issues/2778#issuecomment-638506369 `no_cache` feature sets the cache size to 1 instead of disabling it entirely. This most likely leads to incorrect computation of fees, especially the newly added fee for loading/compiling the contract. We need to fix `no_cache` feature to disable the cache and recompute the fees

**Comment by bowenwang1996** [comment]
Is `no_cache` on by default?

**Comment by willemneal** [comment]
@bowenwang1996 Yep
```toml
near-vm-runner = {path = "../../runtime/near-vm-runner" , features = ["costs_counting", "no_cache"]}
node-runtime = { path = "../../runtime/runtime" , features = ["costs_counting", "no_cache"]}
```
