### ISSUE TITLE
Unable to use function InMemorySigner::from_file (field names mismatch)

### ISSUE THREAD

**Issue by formiat** [near/nearcore#7030]
**Problem:**
Unable to use function `InMemorySigner::from_file`, because field names are different in `struct InMemorySigner` and in credentials file.

In struct we got field `secret_key`, but in credentials file we got `private_key`. Function `InMemorySigner::from_file` uses serde's deserializer, so, when we try to deserialize `struct InMemorySigner`, serde's deserializer doesn't find a match for the field and deserialization fails.

**Solution 1**:
Rename `struct InMemorySigner` field `secret_key` to `private_key`.

**Solution 2**:
Rename credentials' field `private_key` to `secret_key`.

**Problem crate**: `near-crypto`
**Problem file**: `src/signer.rs`

**Versions:**
```toml
near-jsonrpc-client = "0.3.0"
near-jsonrpc-primitives = "0.12.0"
near-primitives = "0.12.0"
near-crypto = "0.12.0"
```
